###
# vkucukcakar/runit
# runit Docker image for service supervision and zombie reaping
# Copyright (c) 2017 Volkan Kucukcakar
# 
# This file is part of vkucukcakar/runit.
# 
# vkucukcakar/runit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# vkucukcakar/runit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# This copyright notice and license must be retained in all files and derivative works.
###


FROM vkucukcakar/base:debian

LABEL maintainer "Volkan Kucukcakar"

# Install and configure runit for Debian (Create /etc/inittab before installing).
RUN touch /etc/inittab \
    && apt-get update -q \
    && apt-get install -y runit

# Clean up the apt cache
RUN rm -rf /var/lib/apt/lists/*



# FOR CHILD IMAGES: Create/COPY your own runit service files (/etc/service/{SERVICENAME}/run) and chmod 755 as follows:

#RUN mkdir -p /etc/service/example/
#COPY debian/example.run /etc/service/example/run
#RUN chmod 755 /etc/service/example/run

# See the bundled example.run runit service file comments for instructions


    
# Set up entrypoint
COPY common/entrypoint.sh /runit/entrypoint.sh
RUN chmod +x /runit/entrypoint.sh
ENTRYPOINT ["/tini", "--", "/runit/entrypoint.sh"]
